SELECT
    u.USER_ID,
    u.NICKNAME AS NICKNAME,
    CONCAT(u.CITY, ' ', u.STREET_ADDRESS1, ' ', IFNULL(u.STREET_ADDRESS2, '')) AS FULL_ADDRESS,
    CONCAT(SUBSTRING(u.TLNO, 1, 3), '-', SUBSTRING(u.TLNO, 4, 4), '-', SUBSTRING(u.TLNO, 8)) AS FORMATTED_TLNO
FROM
    USED_GOODS_USER u
JOIN
    (SELECT
        WRITER_ID,
        COUNT(*) AS POST_COUNT
    FROM
        USED_GOODS_BOARD
    GROUP BY
        WRITER_ID
    HAVING
        COUNT(*) >= 3) b
ON
    u.USER_ID = b.WRITER_ID
ORDER BY
    u.USER_ID DESC;